// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetApiV1BestellungData, GetApiV1BestellungResponse, PatchApiV1BestellungData, PatchApiV1BestellungResponse, PostApiV1BestellungData, DeleteApiV1BestellungByBestellungIdData, DeleteApiV1BestellungByBestellungIdResponse, PostApiV1CheckinByKartenNrData, GetApiV1LoginData, GetApiV1LoginResponse, GetHelloData, GetHelloResponse, GetApiV1CheckinStatusData, GetApiV1CheckinStatusResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Bestellungen
 */
export const getApiV1Bestellung = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1BestellungData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiV1BestellungResponse, unknown, ThrowOnError>({
        url: '/api/v1/bestellung',
        ...options
    });
};

/**
 * Check Bestellung
 */
export const patchApiV1Bestellung = <ThrowOnError extends boolean = false>(options?: Options<PatchApiV1BestellungData, ThrowOnError>) => {
    return (options?.client ?? client).patch<PatchApiV1BestellungResponse, unknown, ThrowOnError>({
        url: '/api/v1/bestellung',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * New Bestellung
 */
export const postApiV1Bestellung = <ThrowOnError extends boolean = false>(options?: Options<PostApiV1BestellungData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
        url: '/api/v1/bestellung',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Bestellung
 */
export const deleteApiV1BestellungByBestellungId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiV1BestellungByBestellungIdData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiV1BestellungByBestellungIdResponse, unknown, ThrowOnError>({
        url: '/api/v1/bestellung/{bestellungId}',
        ...options
    });
};

/**
 * Check In Customer
 */
export const postApiV1CheckinByKartenNr = <ThrowOnError extends boolean = false>(options: Options<PostApiV1CheckinByKartenNrData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
        url: '/api/v1/checkin/{kartenNr}',
        ...options
    });
};

/**
 * Get Customer Checkin-Status
 */
export const getApiV1CheckinStatus = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1CheckinStatusData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiV1CheckinStatusResponse, unknown, ThrowOnError>({
        url: '/api/v1/checkin-status',
        ...options
    });
};

/**
 * Get Message
 */
export const getApiV1Login = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1LoginData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiV1LoginResponse, unknown, ThrowOnError>({
        url: '/api/v1/login',
        ...options
    });
};

/**
 * Hello
 */
export const getHello = <ThrowOnError extends boolean = false>(options?: Options<GetHelloData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHelloResponse, unknown, ThrowOnError>({
        url: '/hello',
        ...options
    });
};