// This file is auto-generated by @hey-api/openapi-ts

export type Bestellung = {
    id?: number;
    benutzerId?: string;
    benutzerEmail?: string;
    anzahlEssenskarte?: number;
    anzahlAbendkarte?: number;
    bezahlt?: boolean;
};

export type BestellungRequest = {
    anzahlEssenskarten?: number;
    anzahlAbendkarten?: number;
};

export type UpdateBestellStatus = {
    id?: number;
    bezahlt?: boolean;
};

export type GetApiV1BestellungData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/bestellung';
};

export type GetApiV1BestellungErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiV1BestellungResponses = {
    /**
     * OK
     */
    200: Array<Bestellung>;
};

export type GetApiV1BestellungResponse = GetApiV1BestellungResponses[keyof GetApiV1BestellungResponses];

export type PatchApiV1BestellungData = {
    body?: UpdateBestellStatus;
    path?: never;
    query?: never;
    url: '/api/v1/bestellung';
};

export type PatchApiV1BestellungErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PatchApiV1BestellungResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiV1BestellungResponse = PatchApiV1BestellungResponses[keyof PatchApiV1BestellungResponses];

export type PostApiV1BestellungData = {
    body?: BestellungRequest;
    path?: never;
    query?: never;
    url: '/api/v1/bestellung';
};

export type PostApiV1BestellungErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiV1BestellungResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1BestellungByBestellungIdData = {
    body?: never;
    path: {
        bestellungId: number;
    };
    query?: never;
    url: '/api/v1/bestellung/{bestellungId}';
};

export type DeleteApiV1BestellungByBestellungIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiV1BestellungByBestellungIdResponse = DeleteApiV1BestellungByBestellungIdResponses[keyof DeleteApiV1BestellungByBestellungIdResponses];

export type PostApiV1CheckinByKartenNrData = {
    body?: never;
    path: {
        kartenNr: string;
    };
    query?: never;
    url: '/api/v1/checkin/{kartenNr}';
};

export type PostApiV1CheckinByKartenNrResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetApiV1LoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login';
};

export type GetApiV1LoginResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetApiV1LoginResponse = GetApiV1LoginResponses[keyof GetApiV1LoginResponses];

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hello';
};

export type GetHelloResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];